### ISSUE TITLE
Google I/O 2014 has stoppped

### ISSUE THREAD

**Issue by terminus06** [google/iosched#105]
I imported iosched to Android Studio 1.0.1 as explained at Building.md.
Although Build is successful, application doesnt work at emulator. "Unfortunatelly, Google I/O 2014 has stopped" error occurs.
Here is the Logcat after run the project.

1983-1983/com.google.samples.apps.iosched E/libprocessgroup﹕ failed to make and chown /acct/uid_10053: Read-only file system
1983-1983/com.google.samples.apps.iosched W/Zygote﹕ createProcessGroup failed, kernel missing CONFIG_CGROUP_CPUACCT?
1983-1983/com.google.samples.apps.iosched I/art﹕ Not late-enabling -Xcheck:jni (already on)
1983-1983/com.google.samples.apps.iosched D/iosched_AnalyticsManag﹕ Analytics manager using DEBUG ANALYTICS PROFILE.
1983-1983/com.google.samples.apps.iosched W/GAV4﹕ Thread[main,5,main]: int configuration name not recognized:  ga_dispatchInterval
1983-1983/com.google.samples.apps.iosched W/GAV4﹕ Thread[main,5,main]: bool configuration name not recognized:  ga_debug
1983-1995/com.google.samples.apps.iosched I/art﹕ Background sticky concurrent mark sweep GC freed 2105(185KB) AllocSpace objects, 2(32KB) LOS objects, 0% free, 1351KB/1363KB, paused 26.956ms total 103.157ms
1983-1983/com.google.samples.apps.iosched D/AndroidRuntime﹕ Shutting down VM
1983-1983/com.google.samples.apps.iosched E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.google.samples.apps.iosched, PID: 1983
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.samples.apps.iosched/com.google.samples.apps.iosched.ui.BrowseSessionsActivity}: java.lang.UnsupportedOperationException: Device does not have package com.google.android.gsf
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.UnsupportedOperationException: Device does not have package com.google.android.gsf
            at com.google.android.gcm.GCMRegistrar.checkDevice(GCMRegistrar.java:83)
            at com.google.samples.apps.iosched.ui.BaseActivity.registerGCMClient(BaseActivity.java:1375)
            at com.google.samples.apps.iosched.ui.BaseActivity.onCreate(BaseActivity.java:254)
            at com.google.samples.apps.iosched.ui.BrowseSessionsActivity.onCreate(BrowseSessionsActivity.java:90)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
1983-2000/com.google.samples.apps.iosched W/GAV4﹕ Thread[GAThread,5,main]: Service unavailable (code=1), will retry.
1983-2011/com.google.samples.apps.iosched W/GAV4﹕ Thread[Service Reconnect,5,main]: Service unavailable (code=1), using local store.

**Comment by egor-n** [comment]
http://stackoverflow.com/questions/11339445/com-google-android-gsf-package-couldnt-be-found

**Comment by terminus06** [comment]
Thank you egor-n, it works now :)
