### ISSUE TITLE
Error Importing To Android Studio

### ISSUE THREAD

**Issue by halfbaked** [google/iosched#116]
Hi guys, 

I followed the detailed build instructions but ran into the following Assertion Error when trying to import 
into Android Studio 0.8.14

    java.lang.AssertionError
    at    com.android.tools.idea.gradle.project.PreSyncChecks.attemptToUpdateGradleVersionInWrapper(PreSyncChecks.java:174)
    at com.android.tools.idea.gradle.project.PreSyncChecks.ensureCorrectGradleSettings(PreSyncChecks.java:72)
    at com.android.tools.idea.gradle.project.PreSyncChecks.canSync(PreSyncChecks.java:53)

Note that from the command line, in the root of the project directory the following was successful

    ./gradlew clean assembleDebug

**Comment by PaulRashidi** [comment]
Now that Android Studio and the Android Gradle plugin received their version 1.0 stamps you'll need to use 1.0 or higher. Prior to 1.0 there were occasional changes to the Android DSL and the Gradle dependency that I believe you're running into.

**Comment by halfbaked** [comment]
sounds about right. thanks for the reply.
