### ISSUE TITLE
OOM error while using BezelImageView

### ISSUE THREAD

**Issue by goonerDroid** [google/iosched#172]
Following is my stacktrace:-
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 846412 byte allocation with 739828 free bytes and 722KB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:942)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
       at com.xyz.zyx.widgets.BezelImageView.onDraw(BezelImageView.java:138)
       at android.view.View.draw(View.java:16472)
       at android.view.View.updateDisplayListIfDirty(View.java:15402)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.View.draw(View.java:16194)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3709)
       at android.support.design.widget.CollapsingToolbarLayout.drawChild(CollapsingToolbarLayout.java:290)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3502)
       at android.view.View.draw(View.java:16475)
       at android.widget.FrameLayout.draw(FrameLayout.java:598)
       at android.support.design.widget.CollapsingToolbarLayout.draw(CollapsingToolbarLayout.java:251)
       at android.view.View.updateDisplayListIfDirty(View.java:15402)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.View.draw(View.java:16194)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3709)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3502)
       at android.view.View.draw(View.java:16475)
       at android.view.View.updateDisplayListIfDirty(View.java:15402)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.View.draw(View.java:16194)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3709)
       at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1077)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3502)
       at android.view.View.draw(View.java:16475)
       at android.view.View.updateDisplayListIfDirty(View.java:15402)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.View.draw(View.java:16194)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3709)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3502)
       at android.view.View.updateDisplayListIfDirty(View.java:15397)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.View.draw(View.java:16194)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3709)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3502)
       at android.view.View.updateDisplayListIfDirty(View.java:15397)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.View.draw(View.java:16194)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3709)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3502)
       at android.view.View.updateDisplayListIfDirty(View.java:15397)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.View.draw(View.java:16194)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3709)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3502)
       at android.view.View.updateDisplayListIfDirty(View.java:15397)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.View.draw(View.java:16194)
       at android.view.ViewGroup.drawChild(ViewGroup.java:3709)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3502)
       at android.view.View.draw(View.java:16475)
       at android.widget.FrameLayout.draw(FrameLayout.java:598)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:3108)
       at android.view.View.updateDisplayListIfDirty(View.java:15402)
       at android.view.View.getDisplayList(View.java:15424)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:310)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:316)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:355)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2889)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2683)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2270)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1264)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6944)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6837)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

This crash occured in Samsung Galaxy S6 running on Lollipop.Is there any need to scale the bitmap which is created inside the onDraw() method of BezelImageView class?

**Comment by JoseAlcerreca** [comment]
Obsolete
