### ISSUE TITLE
App Crash on Android P or Android 6.0 above due to lack of org.apache.http.legacy library

### ISSUE THREAD

**Issue by lamdeyton** [google/iosched#291]
When you click the map tab icon from the home page after a few seconds ,the app will be crashed.
Crash Log is below:
Process: com.google.samples.apps.iosched, PID: 3949
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
        at ep.b(:com.google.android.gms.dynamite_mapsdynamite@13280081@13.2.80 (100400-211705629):3)
        at eo.a(:com.google.android.gms.dynamite_mapsdynamite@13280081@13.2.80 (100400-211705629):4)
        at eq.a(:com.google.android.gms.dynamite_mapsdynamite@13280081@13.2.80 (100400-211705629):55)
        at com.google.maps.api.android.lib6.drd.ap.a(:com.google.android.gms.dynamite_mapsdynamite@13280081@13.2.80 (100400-211705629):11)
        at dx.a(:com.google.android.gms.dynamite_mapsdynamite@13280081@13.2.80 (100400-211705629):17)
        at dx.run(:com.google.android.gms.dynamite_mapsdynamite@13280081@13.2.80 (100400-211705629):65)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/00000032/MapsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000032/MapsDynamite.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at ad.loadClass(:com.google.android.gms.dynamite_dynamiteloader@13280081@13.2.80 (100400-211705629):25)

I'v tried to uselibrary 'org.apache.http.legacy' in the root build.gradle. but it doesn't work.
Finally,I tried to add content: <uses-library android:name="org.apache.http.legacy" android:required="false"/>  to AndroidManifest.xml ,this time it worked.
Hope this issue can be fixed soon.

**Comment by yoavgray** [comment]
@lamdeyton If you're targeting API 28 and above, follow these instructions:
https://developers.google.com/maps/documentation/android-sdk/config#specify_requirement_for_apache_http_legacy_library

**Comment by tilalapradip** [comment]
This link explains why to add the same in manifest
[https://stackoverflow.com/questions/50461881/java-lang-noclassdeffounderrorfailed-resolution-of-lorg-apache-http-protocolve/53828101#53828101](url)

**Comment by AnnuRArya** [comment]
Came across the same issue when Xamarin.Android app was upgraded to Android P .Then came across this article 
![image](https://user-images.githubusercontent.com/47095702/58149201-8248a300-7c7f-11e9-83f8-1ad2316eb347.png)

**Comment by VinayTShetty** [comment]
https://developer.android.com/about/versions/pie/android-9.0-changes-28

<uses-library android:name="org.apache.http.legacy" android:required="false"/>
After adding the above tag the issue remains same...
can anyone provide any solutions
