### ISSUE TITLE
App crashing on start after comment a simple dailog code

### ISSUE THREAD

**Issue by burhankhanzada** [google/iosched#362]
i am learning from this sample and for my purpose i wan to simplify this app to focus on main feature like i want to focus on how `ScheduleFragment` work with `ViewModel` and `Repository` but when i remove code related dialog like this in `ScheduleFragment` its crashing and generating error see below i think which is related to hilt any suggestion on this
```
private fun openSignInDialog() {
        val dialog = SignInDialogFragment()
//        dialog.show(requireActivity().supportFragmentManager, DIALOG_NEED_TO_SIGN_IN)
    }
```

```
2020-11-09 21:26:32.298 29657-29657/? E/es.apps.iosche: Unknown bits set in runtime_flags: 0x8000
2020-11-09 21:26:36.753 29657-29657/com.google.samples.apps.iosched E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.samples.apps.iosched, PID: 29657
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/samples/apps/iosched/model/Tag;
        at com.google.samples.apps.iosched.shared.data.ConferenceDataJsonParser.parseConferenceData(ConferenceDataJsonParser.kt:49)
        at com.google.samples.apps.iosched.shared.data.BootstrapConferenceDataSource.loadAndParseBootstrapData(BootstrapConferenceDataSource.kt:39)
        at com.google.samples.apps.iosched.shared.data.BootstrapConferenceDataSource.getOfflineConferenceData(BootstrapConferenceDataSource.kt:31)
        at com.google.samples.apps.iosched.shared.data.userevent.FakeUserEventDataSource.<clinit>(FakeUserEventDataSource.kt:40)
        at com.google.samples.apps.iosched.shared.di.SharedModule.provideUserEventDataSource(SharedModule.kt:99)
        at com.google.samples.apps.iosched.shared.di.SharedModule_ProvideUserEventDataSourceFactory.provideUserEventDataSource(SharedModule_ProvideUserEventDataSourceFactory.java:33)
        at com.google.samples.apps.iosched.DaggerMainApplication_HiltComponents_ApplicationC.getUserEventDataSource(DaggerMainApplication_HiltComponents_ApplicationC.java:437)
        at com.google.samples.apps.iosched.DaggerMainApplication_HiltComponents_ApplicationC.getSessionAndUserEventRepository(DaggerMainApplication_HiltComponents_ApplicationC.java:521)
        at com.google.samples.apps.iosched.DaggerMainApplication_HiltComponents_ApplicationC.getNotificationAlarmUpdater(DaggerMainApplication_HiltComponents_ApplicationC.java:535)
        at com.google.samples.apps.iosched.DaggerMainApplication_HiltComponents_ApplicationC.getAuthStateUserDataSource(DaggerMainApplication_HiltComponents_ApplicationC.java:549)
        at com.google.samples.apps.iosched.DaggerMainApplication_HiltComponents_ApplicationC.getObserveUserAuthStateUseCase(DaggerMainApplication_HiltComponents_ApplicationC.java:577)
        at com.google.samples.apps.iosched.DaggerMainApplication_HiltComponents_ApplicationC.getSignInViewModelDelegate(DaggerMainApplication_HiltComponents_ApplicationC.java:627)
        at com.google.samples.apps.iosched.DaggerMainApplication_HiltComponents_ApplicationC.getAnalyticsHelper(DaggerMainApplication_HiltComponents_ApplicationC.java:641)
        at com.google.samples.apps.iosched.DaggerMainApplication_HiltComponents_ApplicationC.injectMainApplication2(DaggerMainApplication_HiltComponents_ApplicationC.java:1106)
        at com.google.samples.apps.iosched.DaggerMainApplication_HiltComponents_ApplicationC.injectMainApplication(DaggerMainApplication_HiltComponents_ApplicationC.java:1081)
        at com.google.samples.apps.iosched.Hilt_MainApplication.onCreate(Hilt_MainApplication.java:42)
        at com.google.samples.apps.iosched.MainApplication.onCreate(MainApplication.kt:46)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1182)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6460)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.samples.apps.iosched.model.Tag" on path: DexPathList[[zip file "/data/app/com.google.samples.apps.iosched-bROwMrMw6vFC-g2tgOIpfw==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.samples.apps.iosched-bROwMrMw6vFC-g2tgOIpfw==/lib/x86, /data/app/com.google.samples.apps.iosched-bROwMrMw6vFC-g2tgOIpfw==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
2020-11-09 21:26:36.753 29657-29657/com.google.samples.apps.iosched E/AndroidRuntime: 	... 27 more
```

**Comment by jdkoren** [comment]
This does not appear to have anything to do with the dialog. What happens when you run the app without any changes?

**Comment by iambuntoo** [comment]
its run fine when i un comment and yeah i know this not related to dialog in any way that's what annoys me

**Comment by iambuntoo** [comment]
well when investigating this issue i tried which debug build and its work fine but stagging build it won't
