### ISSUE TITLE
no com.google.dagger:hilt-android dependency was found

### ISSUE THREAD

**Issue by dmbrechko** [google/iosched#403]
Android Studio Bumblebee 2021.1.1 Patch 1
Gradle build fails with exception:
* Exception is:
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':mobile'.
Caused by: java.lang.IllegalStateException: The Hilt Android Gradle plugin is applied but no com.google.dagger:hilt-android dependency was found.
	at dagger.hilt.android.plugin.HiltGradlePlugin.verifyDependencies(HiltGradlePlugin.kt:471)
	at dagger.hilt.android.plugin.HiltGradlePlugin.apply$lambda-2(HiltGradlePlugin.kt:73)

**Comment by Damercy** [comment]
Requires updation of AGP & Hilt gradle plugin. Already opened [this PR](https://github.com/google/iosched/pull/406#issue-1167388183) to get this issue resolved.
